### ISSUE TITLE
Can not install applications on the actual iOS machine

### ISSUE THREAD

**Issue by yutailang0119** [ishkawa/DIKit#53]
# Environment 

- DIKit 0.3.2
- Xcode 9.3.1
    - Swift 4.1

# Current behavior

There is no problem with the simulator, but applications depend on DIKit can not be installed on the actual iOS machine.

> -[MIExecutableBundle codeSigningInfoByValidatingResources:performingOnlineAuthorization:ignoringCachedSigningInfo:checkingTrustCacheIfApplicable:error:]: 759: Code signing identifier (DIKit-5555494433789024584e33efa5e65138640f2c13) does not match bundle identifier (DIKit) for /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.boLOcV/extracted/Xxx.app/Frameworks/DIKit.framework

<details>
<summary>Xcode Alert</summary>
<img width="532" alt="image" src="https://user-images.githubusercontent.com/9477376/40435052-c4369956-5eea-11e8-925d-dd3c02ca8671.png">
</details>

# Why

I think that this problem is caused by Swift 4.1 and SwiftPM.

Add `PRODUCT_BUNDLE_IDENTIFIER = DIKit;` to DIKit.xcodeproj/project.pbxproj after bfe0dc0.
* https://github.com/ishkawa/DIKit/commit/bfe0dc0466cb521e185e61a068b563c2530c7193#diff-a9f7da3baa633faf01498494fa2ffcb5R2029
* https://github.com/ishkawa/DIKit/commit/bfe0dc0466cb521e185e61a068b563c2530c7193#diff-a9f7da3baa633faf01498494fa2ffcb5R2053

This should be `org.ishkawa.DIKit` instead of `DIKit`.
And this causes unexpected behavior to [DIKit_Info.plist](https://github.com/ishkawa/DIKit/blob/master/DIKit.xcodeproj/DIKit_Info.plist#L9).

## Example via Carthage
<details>
<summary>/Carthage/Build/iOS/DIKit.framework/Info.plist</summary>
<img width="912" alt="infoplist" src="https://user-images.githubusercontent.com/9477376/40434140-adca9034-5ee8-11e8-8d48-8219a640b1b6.png">
</details>

# Expected Behavior

Unfortunately, I have no idea with a way to easily solve it.
However, I confirmed that it can be avoided by revert bfe0dc0.
https://github.com/yutailang0119/DIKit/commit/5dabb486277a920b027f501799ab3c80f0b889f7

###### 

I'm investigating with @niwatako and @ikesyo

**Comment by ishkawa** [comment]
Hi, @yutailang0119.

Thank you for the detailed report, and sorry for inconvenience.
I've just submitted a PR #54 to fix this issue by the simplest way. Could you confirm it fixes this issue?
You can test the PR by `github "ishkawa/DIKit" "fix-bundle-identifier"`.

**Comment by yutailang0119** [comment]
Hi @ishkawa 

Thank you for your support.

I confirmed that #54 resolve this issue.
However, I'm a little worried that new problems will occur by setting bundle identifier after generation.

**Comment by ishkawa** [comment]
Thanks! I'm going to merge #54 and release 0.3.3 to resolve this issue instantly.

To prevent us from overlooking this kind of issue, I would like to hear more about your consideration of possible problem. If we always use xcodeproj generated from `make generate_xcodeproj` and never edit it directly, is the problem still possible? I think no one need to modify bundle identifier after `make generate_xcodeproj`.

**Comment by yutailang0119** [comment]
Thank you for solving!

I also think that it is desirable not to edit what is generated by `swift package generate-xcodeproj`.

But, this problem is due to the change of SwiftPM.
I can not understand the direct cause, so I'm trying to investigate [generate().swift](https://github.com/apple/swift-package-manager/blob/master/Sources/Xcodeproj/generate().swift)

Unfortunately, in order to solve quickly, we need to stop generating with SwiftPM.
Because, SwiftPM does not consider iOS.

**Comment by JonasVautherin** [comment]
I have the exact same issue (in another project), but I don't understand how to solve it. Do you have a better understanding of it? Why is Carthage adding this weird number after the bundle name (`DIKit-5555494433789024584e33efa5e65138640f2c13`)?

**Comment by ishkawa** [comment]
From DIKit 0.4.0, we started to maintain xcodeproj generated by Xcode, so I think this issue no longer appears. Feel free to reopen this issue when you still have this issue with DIKit 0.4.0.
